# fly.toml app configuration file generated for typeblade on 2024-01-01T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "typeblade"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"
  LOG_LEVEL = "info"
  RATE_LIMIT_WINDOW_MS = "900000"
  RATE_LIMIT_MAX_REQUESTS = "100"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 9091
  path = "/metrics"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0 