# fly.toml app configuration file generated for typeblade on 2025-07-07T01:58:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'typeblade'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
